- name: Install Nginx
  ansible.builtin.apt:
    name: nginx
    state: present
    update_cache: true

- name: Ensure nginx is running and enabled
  ansible.builtin.systemd:
    name: nginx
    state: started
    enabled: true

- name: Create web root directory
  ansible.builtin.file:
    path: /var/www/html
    state: directory
    owner: www-data
    group: www-data
    mode: '0755'

- name: Deploy static index.html
  ansible.builtin.copy:
    content: |
      <!DOCTYPE html>
      <html>
      <head><title>DevOps Course Work</title></head>
      <body>
        <h1>Netology course work of LyutikovAV</h1>
      </body>
      </html>
    dest: /var/www/html/index.html
    owner: www-data
    group: www-data
    mode: '0644'

  notify: Restart Nginx
